INSERT INTO Song(Song_id, Title, File, Artist, Version) 
VALUES 
(1, "Magnolia", "Magnolia-Original.mp4", "Playboi Carti", "Original"),
(2, "Shoota", "Shoota-Original.mp4", "Playboi Carti", "Original"),
(3, "FlatBed Freestyle", "FlatBed Freestyle-Original.mp4", "Playboi Carti", "Original"),
(4, "Sky", "Sky-Original.mp4", "Playboi Carti", "Original"),
(5, "Location", "Location-Original.mp4", "Playboi Carti", "Original"),
(6, "Long Time", "Long Time-Original.mp4", "Playboi Carti", "Original"),
(7, "R.I.P.", "R.I.P.-Original.mp4", "Playboi Carti", "Original"),
(8, "Cancun", "Cancun-Original.mp4", "Playboi Carti", "Original"),
(9, "No Time", "No Time-Original.mp4", "Playboi Carti", "Original"),
(10, "Flex", "Flex-Original.mp4", "Playboi Carti", "Original"),
(11, "New Choppa", "New Choppa-Original.mp4", "Playboi Carti", "Original"),
(12, "New Choppa", "New Choppa-Acoustic.mp4", "Playboi Carti", "Acoustic"),
(13, "Poke It Out", "Poke It Out-Original.mp4", "Playboi Carti", "Original"),
(14, "Choppa Won't Miss", "Choppa Won't Miss-Original.mp4", "Playboi Carti", "Original"),
(15, "Choppa Won't Miss", "Choppa Won't Miss-Acoustic.mp4", "Playboi Carti", "Acoustic"),
(16, "Yah Mean", "Yah Mean-Original.mp4", "Playboi Carti", "Original"),
(17, "Yah Mean", "Yah Mean-Clean.mp4", "Playboi Carti", "Clean"),
(18, "Fetti", "Fetti-Original.mp4", "Playboi Carti", "Original"),
(19, "Molly", "Molly-Original.mp4", "Playboi Carti", "Original"),
(20, "Lean 4 Real", "Lean 4 Real-Original.mp4", "Playboi Carti", "Original"),
(21, "RIP Fredo", "RIP Fredo-Original.mp4", "Playboi Carti", "Original"),
(22, "Home (KOD)", "Home (KOD)-Original.mp4", "Playboi Carti", "Original"),
(23, "Home (KOD)", "Home (KOD)-Clean.mp4", "Playboi Carti", "Clean"),
(24, "Foreign", "Foreign-Original.mp4", "Playboi Carti", "Original"),
(25, "Fell In Luv", "Fell In Luv-Original.mp4", "Playboi Carti", "Original"),
(26, "Fell In Luv", "Fell In Luv-Acoustic.mp4", "Playboi Carti", "Acoustic"),
(27, "Middle of the Summer", "Middle of the Summer-Original.mp4", "Playboi Carti", "Original"),
(28, "Lame Niggaz", "Lame Niggaz-Original.mp4", "Playboi Carti", "Original"),
(29, "Lame Niggaz", "Lame Niggaz-Clean.mp4", "Playboi Carti", "Clean"),
(30, "Kelly K", "Kelly K-Original.mp4", "Playboi Carti", "Original"),
(31, "Dothatshit!", "Dothatshit!-Original.mp4", "Playboi Carti", "Original"),
(32, "Talk", "Talk-Original.mp4", "Playboi Carti", "Original"),
(33, "Talk", "Talk-Acoustic.mp4", "Playboi Carti", "Acoustic"),
(34, "Wokeuplikethis*", "Wokeuplikethis*-Original.mp4", "Playboi Carti", "Original"),
(35, "Location", "Location-Original.mp4", "Playboi Carti", "Original"),
(36, "Half & Half", "Half & Half-Original.mp4", "Playboi Carti", "Original"),
(37, "Half & Half", "Half & Half-Acoustic.mp4", "Playboi Carti", "Acoustic"),
(38, "Let It Go", "Let It Go-Original.mp4", "Playboi Carti", "Original"),
(39, "Shawty In Love", "Shawty In Love-Original.mp4", "Playboi Carti", "Original"),
(40, "Back Up", "Back Up-Original.mp4", "Playboi Carti", "Original"),
(41, "Back Up", "Back Up-Acoustic.mp4", "Playboi Carti", "Acoustic");

INSERT INTO Contributor(Contributor_id, ContributorName) 
VALUES 
(1, "Lil Uzi Vert"),
(2, "Gunna"),
(3, "Leven Kali"),
(4, "A$AP Rocky"),
(5, "Nicki Minaj"),
(6, "Young Thug"),
(7, "Da$h"),
(8, "Maxo Kream"),
(9, "Skepta"),
(10, "Young Nudy"),
(11, "Bryson Tiller"),
(12, "Red Coldhearted"),
(13, "Lil Yachty"),
(14, "ICYTWAT"),
(15, "ASAP Ferg"),
(16, "KILLY");

INSERT INTO Feature(Song_id, Contributor_id, Role) 
VALUES
(2, 1, "Featured Artist"),
(9, 2, "Featured Artist"),
(10, 3, "Featured Artist"),
(11, 4, "Featured Artist"),
(12, 4, "Featured Artist"),
(13, 5, "Featured Artist"),
(14, 6, "Featured Artist"),
(15, 6, "Featured Artist"),
(18, 7, "Featured Artist"),
(18, 8, "Featured Artist"),
(20, 9, "Featured Artist"),
(21, 10, "Featured Artist"),
(25, 11, "Featured Artist"),
(26, 11, "Featured Artist"),
(27, 12, "Featured Artist"),
(28, 13, "Featured Artist"),
(29, 13, "Featured Artist"),
(32, 14, "Featured Artist"),
(33, 14, "Featured Artist"),
(34, 1, "Featured Artist"),
(35, 15, "Featured Artist"),
(39, 16, "Featured Artist");
